
modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="howny"
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Howny" #mandatory
logoFile="howny.png"
authors="Rosyo"

description='''
Howny! Welcome to the world of bees!

Become a beekeeper and use honey to enhance your survival experience!
'''

[[dependencies.howny]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.howny]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
